<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ScImport extends Model
{
    public $fillable = [
        'period',
        'year',
        'month',
        'programPartner',
        'partner',
        'campSettlement',
        'siteName',
        'campId',
        'reportMode',
        'ageGroup',
        'beginningMonth_M',
        'beginningMonth_F',
        'beginningMonthTotal',
        'newAdmissionWfh_M',
        'newAdmissionWfh_F',
        'newAdmissionMuc_M',
        'newAdmissionMuc_F',
        'newAdmissionEdema_M',
        'newAdmissionEdema_F',
        'newAdmissionRelapse_M',
        'newAdmissionRelapse_F',
        'totalNewAdmission_M',
        'totalNewAdmission_F',
        'totalNewAdmission',
        'readmissionAfterDefault_M',
        'readmissionAfterDefault_F',
        'transferInFromOtp_M',
        'transferInFromOtp_F',
        'totalEntries_M',
        'totalEntries_F',
        'totalEntries',
        'recovered_M',
        'recovered_F',
        'death_M',
        'death_F',
        'default_M',
        'default_F',
        'nonRecovered_M',
        'nonRecovered_F',
        'unknown_M',
        'unknown_F',
        'medicalTransfer_M',
        'medicalTransfer_F',
        'transferToOtp_M',
        'transferToOtp_F',
        'totalDischarged_M',
        'totalDischarged_F',
        'totalDischarged',
        'exitOther_M',
        'exitOther_F',
        'totalExit_M',
        'totalExit_F',
        'totalExit',
        'totalEndOfMonth_M',
        'totalEndOfMonth_F',
        'totalEndOfMonth',
        'alos',
        'awg',
    ];
}
