<?php

namespace App\Imports;

use App\BsfpImport;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithStartRow;

class BsfpexcelImport implements ToModel,WithStartRow
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function startRow(): int
    {
        return 4;
    }
    public function model(array $row)
    {
        return new BsfpImport([
            'period'=> $row[0],
            'year'=> $row[1],
            'month'=> $row[2],
            'programPartner'=> $row[3],
            'partner'=> $row[4],
            'campSettlement'=> $row[5],
            'siteName'=> $row[6],
            'campId'=> $row[7],

        'beginningMonthTotal'=> $row[8],
        'beginningMonth23M'=> $row[9],
        'beginningMonth23F'=> $row[10],
        'beginningMonth59M'=> $row[11],
        'beginningMonth59F'=> $row[12],
        'newEnrolmentTotal'=> $row[13],
        'newEnrolment23M'=> $row[14],
        'newEnrolment23F'=> $row[15],
        'newEnrolment59M'=> $row[16],
        'newEnrolment59F'=> $row[17],
        'readmissionAfterDefaultTotal'=> $row[18],
        'readmissionAfterDefault23M'=> $row[19],
        'readmissionAfterDefault23F'=> $row[20],
        'readmissionAfterDefault59M'=> $row[21],
        'readmissionAfterDefault59F'=> $row[22],
        'transferInFromOtherBsfpTotal'=> $row[23],
        'transferInFromOtherBsfp23M'=> $row[24],
        'transferInFromOtherBsfp23F'=> $row[25],
        'transferInFromOtherBsfp59M'=> $row[26],
        'transferInFromOtherBsfp59F'=> $row[27],
        'returnFromMamTreatmentTotal'=> $row[28],
        'returnFromMamTreatment23M'=> $row[29],
        'returnFromMamTreatment23F'=> $row[30],
        'returnFromMamTreatment59M'=> $row[31],
        'returnFromMamTreatment59F'=> $row[32],
        'totalAdmission'=> $row[33],
        'totalAdmission23M'=> $row[34],
        'totalAdmission23F'=> $row[35],
        'totalAdmission59M'=> $row[36],
        'totalAdmission59F'=> $row[37],
        'discharge59Total'=> $row[38],
        'discharge23M'=> $row[39],
        'discharge23F'=> $row[40],
        'discharge59M'=> $row[41],
        'discharge59F'=> $row[42],
        'defaulterTotal'=> $row[43],
        'defaulter23M'=> $row[44],
        'defaulter23F'=> $row[45],
        'defaulter59M'=> $row[46],
        'defaulter59F'=> $row[47],
        'deathTotal'=> $row[48],
        'death23M'=> $row[49],
        'death23F'=> $row[50],
        'death59M'=> $row[51],
        'death59F'=> $row[52],
        'totalTransferOut'=> $row[53],
        'totalTransferOut23M'=> $row[54],
        'totalTransferOut23F'=> $row[55],
        'totalTransferOut59M'=> $row[56],
        'totalTransferOut59F'=> $row[57],
        'transferToSamTotal'=> $row[58],
        'transferToSam23M'=> $row[59],
        'transferToSam23F'=> $row[60],
        'transferToSam59M'=> $row[61],
        'transferToSam59F'=> $row[62],
        'transferToMamTotal'=> $row[63],
        'transferToMam23M'=> $row[64],
        'transferToMam23F'=> $row[65],
        'transferToMam59M'=> $row[66],
        'transferToMam59F'=> $row[67],
        'othersTotal'=> $row[68],
        'others23M'=> $row[69],
        'others23F'=> $row[70],
        'others59M'=> $row[71],
        'others59F'=> $row[72],
        'totalExits'=> $row[73],
        'exits23M'=> $row[74],
        'exits23F'=> $row[75],
        'exits59M'=> $row[76],
        'exits59F'=> $row[77],
        'atTheEndTotal'=> $row[78],
        'atTheEnd23M'=> $row[79],
        'atTheEnd23F'=> $row[80],
        'atTheEnd59M'=> $row[81],
        'atTheEnd59F'=> $row[82],
        'reachedTotal'=> $row[83],
        'reached23M'=> $row[84],
        'reached23F'=> $row[85],
        'reached59M'=> $row[86],
        'reached59F'=> $row[87],
        'growthMonitoredTotal'=> $row[88],
        'growthMonitored23M'=> $row[89],
        'growthMonitored23F'=> $row[90],
        'growthMonitored59M'=> $row[91],
        'growthMonitored59F'=> $row[92],
        'mamTotal'=> $row[93],
        'samTotal'=> $row[94],
        'prevalenceOfWasting_AcuteMalnutrition'=> $row[95],
        'stunting'=> $row[96],
        'prevalenceOfStunting'=> $row[97],
        'absentees'=> $row[98],
        'atTheBeginningOfTheMonthPlw'=> $row[99],
        'newAdmissionPlw'=> $row[100],
        'readmissionAfterDefault'=> $row[101],
        'transferInFromOtherBsfpPlw'=> $row[102],
        'referFromTsfp'=> $row[103],
        'others2'=> $row[104],
        'totalAdmissionPlw'=> $row[105],
        'dischargePlw'=> $row[106],
        'transferToOtherTsfpPlw'=> $row[107],
        'transferOutOtherBsfpPlw'=> $row[108],
        'defaulterPlw'=> $row[109],
        'deathPlw'=> $row[110],
        'unexpectedDiscontinuationPregnancy'=> $row[111],
        'otherPlw'=> $row[112],
        'totalExistPlw'=> $row[113],
        'totalBeneficiaryAtTheEndPLW'=> $row[114],
        'reachedBeneficiariesBsfp'=> $row[115],
        'absentees2'=> $row[116],
        'wsb_distributedPlw'=> $row[117],
        'vegetableOilDistributedPlw'=> $row[118],
        'otherSpecifyPlw'=> $row[119],
        ]);
    }
}
