<?php

namespace App\Imports;

use App\TsfpImport;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithStartRow;

class TsfpexcelImport implements ToModel,WithStartRow
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function startRow(): int
    {
        return 4;
    }
    public function model(array $row)
    {
        return new TsfpImport([
            'period'=> $row[0],
            'year'=> $row[1],
            'month'=> $row[2],
            'programPartner'=> $row[3],
            'partner'=> $row[4],
            'campSettlement'=> $row[5],
            'siteName'=> $row[6],
            'campId'=> $row[7],
            'beginningMonthTotal'=> $row[8],
            'beginningMonth23M'=> $row[9],
            'beginningMonth23F'=> $row[10],
            'beginningMonth59M'=> $row[11],
            'beginningMonth59F'=> $row[12],
            'newEnrolmentMuacTotal'=> $row[13],
            'newEnrolmentMuac23M'=> $row[14],
            'newEnrolmentMuac23F'=> $row[15],
            'newEnrolmentMuac59M'=> $row[16],
            'newEnrolmentMuac59F'=> $row[17],
            'newEnrolmentWfhTotal'=> $row[18],
            'newEnrolmentWfh23M'=> $row[19],
            'newEnrolmentWfh23F'=> $row[20],
            'newEnrolmentWfh59M'=> $row[21],
            'newEnrolmentWfh59F'=> $row[22],
            'readmissionAfterDefaultTotal'=> $row[23],
            'readmissionAfterDefault23M'=> $row[24],
            'readmissionAfterDefault23F'=> $row[25],
            'readmissionAfterDefault59M'=> $row[26],
            'readmissionAfterDefault59F'=> $row[27],
            'readmissionAfterRecoveryTotal'=> $row[28],
            'readmissionAfterRecovery23M'=> $row[29],
            'readmissionAfterRecovery23F'=> $row[30],
            'readmissionAfterRecovery59M'=> $row[31],
            'readmissionAfterRecovery59F'=> $row[32],
            'transferInFromTsfpTotal'=> $row[33],
            'transferInFromTsfp23M'=> $row[34],
            'transferInFromTsfp23F'=> $row[35],
            'transferInFromTsfp59M'=> $row[36],
            'transferInFromTsfp59F'=> $row[37],
            'returnFromSamTotal'=> $row[38],
            'returnFromSam23M'=> $row[39],
            'returnFromSam23F'=> $row[40],
            'returnFromSam59M'=> $row[41],
            'returnFromSam59F'=> $row[42],
            'admissionTotal'=> $row[43],
            'admission23M'=> $row[44],
            'admission23F'=> $row[45],
            'admission59M'=> $row[46],
            'admission59F'=> $row[47],
            'dischargeCuredToBsfpTotal'=> $row[48],
            'dischargeCuredToBsfp23M'=> $row[49],
            'dischargeCuredToBsfp23F'=> $row[50],
            'dischargeCuredToBsfp59M'=> $row[51],
            'dischargeCuredToBsfp59F'=> $row[52],
            'defaultTotal'=> $row[53],
            'default23M'=> $row[54],
            'default23F'=> $row[55],
            'default59M'=> $row[56],
            'default59F'=> $row[57],
            'deathTotal'=> $row[58],
            'death23M'=> $row[59],
            'death23F'=> $row[60],
            'death59M'=> $row[61],
            'death59F'=> $row[62],
            'nonResponseTotal'=> $row[63],
            'nonResponse23M'=> $row[64],
            'nonResponse23F'=> $row[65],
            'nonResponse59M'=> $row[66],
            'nonResponse59F'=> $row[67],
            'transferToSamTreatmentTotal'=> $row[68],
            'transferToSamTreatment23M'=> $row[69],
            'transferToSamTreatment23F'=> $row[70],
            'transferToSamTreatment59M'=> $row[71],
            'transferToSamTreatment59F'=> $row[72],
            'transferOutToTsfpTotal'=> $row[73],
            'transferOutToTsfp23M'=> $row[74],
            'transferOutToTsfp23F'=> $row[75],
            'transferOutToTsfp59M'=> $row[76],
            'transferOutToTsfp59F'=> $row[77],
            'othersTotal'=> $row[78],
            'others23M'=> $row[79],
            'others23F'=> $row[80],
            'others59M'=> $row[81],
            'others59F'=> $row[82],
            'exitTotal'=> $row[83],
            'exit23M'=> $row[84],
            'exit23F'=> $row[85],
            'exit59M'=> $row[86],
            'exit59F'=> $row[87],
            'endOfMonthTotal'=> $row[88],
            'endOfMonth23M'=> $row[89],
            'endOfMonth23F'=> $row[90],
            'endOfMonth59M'=> $row[91],
            'endOfMonth59F'=> $row[92],
            'reachedTotal'=> $row[93],
            'reached23M'=> $row[94],
            'reached23F'=> $row[95],
            'reached59M'=> $row[96],
            'reached59F'=> $row[97],
            'curedRate'=> $row[98],
            'deathRate'=> $row[99],
            'defaultRate'=> $row[100],
            'nonResponderRate'=> $row[101],
            'averageGainOfWeight'=> $row[102],
            'averageLengthOfStay'=> $row[103],
            'atTheBeginningOfTheMonthPlw'=> $row[104],
            'newAdmissionPlw'=> $row[105],
            'readmissionAfterBeingdefault'=> $row[106],
            'referFromBsfpPlw'=> $row[107],
            'transferInFromOtherTsfpPlw'=> $row[108],
            'otherVulnerableGroups'=> $row[109],
            'totalAdmissionPlw'=> $row[110],
            'dischargeCuredPlwToBsfp'=> $row[111],
            'dischargePlw'=> $row[112],
            'transferOutToOtherTsfpPlw'=> $row[113],
            'defaulterPlw'=> $row[114],
            'deathPlw'=> $row[115],
            'unexpectedDiscontinuationOfPregnancy'=> $row[116],
            'otherPlw'=> $row[117],
            'totalExistPlw'=> $row[118],
            'totalBeneficiaryAtTheEndPlw'=> $row[119],
            'wsbDistributedPlw'=> $row[120],
            'vegetableOilDistributedPlw'=> $row[121],
            'otherPleaseSpecifyPlw'=> $row[122],
            'tsfpChildNewAdmissionM'=> $row[123],
            'tsfpChildNewAdmissionF'=> $row[124],
            'tsfpChildNewAdmission23M'=> $row[125],
            'tsfpChildNewAdmission23F'=> $row[126],
            'tsfpChildNewAdmission59M'=> $row[127],
            'tsfpChildNewAdmission59F'=> $row[128],
            'newAdmission'=> $row[129],
            'newAdmissionTotal'=> $row[130],
        ]);
    }


}
